name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js 20
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies (use npm install instead of npm ci)
      - run: npm install

      # 4. Build React app
      - run: npm run build

      # 5. Prepare GitHub Pages
      - uses: actions/configure-pages@v5

      # 6. Upload build folder
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
